import { Category } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-road-pothole',
    code: 'ROAD_POTHOLE',
    name: 'Pothole & Surface Damage',
    description: 'Potholes, asphalt crumbling, and sharp pavement depressions',
    baseSeverityWeight: 1.2,
    defaultSlaHours: 48,
    responsibleDepartment: 'Public Works & Roads Dept',
    iconName: 'Construction',
  },
  {
    id: 'cat-drainage-overflow',
    code: 'DRAINAGE_OVERFLOW',
    name: 'Drainage & Sewage Leak',
    description: 'Open manholes, blocked storm gutters, and raw sewage overflow',
    baseSeverityWeight: 1.4,
    defaultSlaHours: 24,
    responsibleDepartment: 'Drainage, Sewerage & Stormwater',
    iconName: 'Droplets',
  },
  {
    id: 'cat-garbage-dump',
    code: 'GARBAGE_DUMP',
    name: 'Garbage & Solid Waste Pile',
    description: 'Illegal road dumps, overflowing community bins, toxic debris',
    baseSeverityWeight: 1.0,
    defaultSlaHours: 36,
    responsibleDepartment: 'Solid Waste Management Cell',
    iconName: 'Trash2',
  },
  {
    id: 'cat-streetlight-outage',
    code: 'STREETLIGHT_OUTAGE',
    name: 'Broken Streetlight / Dark Spot',
    description: 'Non-functional lamps, dangling cables, and hazardous dark zones',
    baseSeverityWeight: 0.85,
    defaultSlaHours: 72,
    responsibleDepartment: 'Electrical & Street Lighting Cell',
    iconName: 'Lightbulb',
  },
  {
    id: 'cat-water-burst',
    code: 'WATER_SUPPLY_BURST',
    name: 'Clean Water Pipeline Burst',
    description: 'High-pressure clean water line rupture flooding road corridors',
    baseSeverityWeight: 1.5,
    defaultSlaHours: 12,
    responsibleDepartment: 'Water Supply & Sanitation',
    iconName: 'Waves',
  },
  {
    id: 'cat-others',
    code: 'OTHERS',
    name: 'Other Civic Issue',
    description: 'Any other civic infrastructure problem not covered by the categories above',
    baseSeverityWeight: 1.0,
    defaultSlaHours: 72,
    responsibleDepartment: 'Triage & Unassigned',
    iconName: 'HelpCircle',
  },
];