export type SupportedLanguage = 'en' | 'hi' | 'ta' | 'te' | 'kn' | 'bn' | 'mr' | 'gu';

export interface LanguageMeta {
  code: SupportedLanguage;
  name: string;
  nativeName: string;
  speechCode: string;
}

export const SUPPORTED_LANGUAGES: LanguageMeta[] = [
  { code: 'en', name: 'English', nativeName: 'English', speechCode: 'en-IN' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', speechCode: 'hi-IN' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', speechCode: 'ta-IN' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', speechCode: 'te-IN' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', speechCode: 'kn-IN' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', speechCode: 'bn-IN' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', speechCode: 'mr-IN' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', speechCode: 'gu-IN' },
];

export const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    appTitle: 'CivicResolve',
    tagline: 'AI-Powered Community Infrastructure Intelligence',
    citizenMode: 'Citizen Portal',
    officerMode: 'Municipal Admin Portal',
    reportIssue: 'Report an Issue',
    reportSubtitle: 'Capture or upload civic issues for automated AI analysis and rapid municipal dispatch.',
    takePhoto: 'Take Photo / Upload Image',
    voiceInput: 'Voice Report (Speak in your language)',
    listening: 'Listening... Please describe the issue',
    locationVerified: 'GPS Location Verified',
    onSiteToggle: 'I am physically at this location',
    categorySelect: 'Infrastructure Category',
    describePlaceholder: 'Describe the issue or speak using the mic...',
    submitting: 'Analyzing with Google Gemini & Submitting...',
    submitReport: 'Submit Verified Civic Report',
    priorityScore: 'Priority Score',
    reportsCount: 'Reports',
    upvotes: 'I Also Faced This',
    statusReported: 'Reported',
    statusInReview: 'In Review',
    statusInProgress: 'In Progress',
    statusResolved: 'Resolved',
    geminiAnalysis: 'Google Gemini Multimodal Vision AI',
    severity: 'Structural Severity',
    confidence: 'AI Confidence',
    hazard: 'Public Hazard Assessment',
    remediation: 'Suggested Remediation',
    duplicateNotice: 'Duplicate Detected: Merged with nearby report within 25m. Priority increased!',
    novelNotice: 'New issue registered and dispatched to municipal ward engineers.',
    filterAll: 'All Categories',
    filterHighPriority: 'Critical Priority (≥ 3.5)',
    filterPending: 'Action Required',
    assignWorker: 'Assign Field Crew',
    resolveIssue: 'Mark Resolved & Upload Proof',
  },
  hi: {
    appTitle: 'सिविक रिज़ॉल्व',
    tagline: 'एआई-संचालित सामुदायिक बुनियादी ढांचा समाधान',
    citizenMode: 'नागरिक पोर्टल',
    officerMode: 'नगर निगम अधिकारी पोर्टल',
    reportIssue: 'समस्या दर्ज करें',
    reportSubtitle: 'त्वरित समाधान के लिए नागरिक बुनियादी ढांचे की समस्याओं की फोटो लें या अपलोड करें।',
    takePhoto: 'फोटो लें या अपलोड करें',
    voiceInput: 'बोलकर बताएं (अपनी भाषा में बोलें)',
    listening: 'सुन रहे हैं... कृपया समस्या का वर्णन करें',
    locationVerified: 'जीपीएस स्थान सत्यापित',
    onSiteToggle: 'मैं व्यक्तिगत रूप से इस स्थान पर मौजूद हूँ',
    categorySelect: 'समस्या की श्रेणी',
    describePlaceholder: 'समस्या का विवरण दें या माइक का उपयोग करें...',
    submitting: 'Google Gemini द्वारा विश्लेषण व सबमिट हो रहा है...',
    submitReport: 'सत्यापित रिपोर्ट दर्ज करें',
    priorityScore: 'प्राथमिकता स्कोर',
    reportsCount: 'दर्ज रिपोर्ट',
    upvotes: 'मुझे भी इस समस्या का सामना हुआ',
    statusReported: 'दर्ज की गई',
    statusInReview: 'समीक्षाधीन',
    statusInProgress: 'कार्य प्रगति पर है',
    statusResolved: 'समाधान हो गया',
    geminiAnalysis: 'Google Gemini मल्टीमॉडल विज़न विश्लेषण',
    severity: 'क्षति की गंभीरता',
    confidence: 'एआई सटीकता',
    hazard: 'सार्वजनिक जोखिम मूल्यांकन',
    remediation: 'अनुशंसित निवारण',
    duplicateNotice: 'समान समस्या मिली: 25 मीटर के दायरे में अन्य रिपोर्ट के साथ जोड़ा गया। प्राथमिकता बढ़ाई गई!',
    novelNotice: 'नई समस्या दर्ज की गई और वार्ड इंजीनियर को प्रेषित की गई।',
    filterAll: 'सभी श्रेणियां',
    filterHighPriority: 'अति-गंभीर प्राथमिकता (≥ 3.5)',
    filterPending: 'कार्रवाई अपेक्षित',
    assignWorker: 'कार्यकर्ता नियुक्त करें',
    resolveIssue: 'समाधान पूरा करें और प्रमाण जोड़ें',
  },
  ta: {
    appTitle: 'சிவிக் ரிசால்வ்',
    tagline: 'செயற்கை நுண்ணறிவு அடிப்படையிலான மக்கள் கட்டமைப்பு தளம்',
    citizenMode: 'குடிமக்கள் போர்டல்',
    officerMode: 'மாநகராட்சி நிர்வாக போர்டல்',
    reportIssue: 'புகார் பதிவு செய்',
    reportSubtitle: 'நகராட்சி விரைவு நடவடிக்கைக்காக உள்கட்டமைப்பு புகார்களை பதிவு செய்யவும்.',
    takePhoto: 'புகைப்படம் எடு / பதிவேற்று',
    voiceInput: 'குரல் மூலம் பதிவு செய்க',
    listening: 'கேட்கிறது... சிக்கலை விவரிக்கவும்',
    locationVerified: 'ஜி.பி.எஸ் இருப்பிடம் சரிபார்க்கப்பட்டது',
    onSiteToggle: 'நான் இந்த இடத்தில் உள்ளேன்',
    categorySelect: 'புகார் வகை',
    describePlaceholder: 'சிக்கலை விவரிக்கவும் அல்லது மைக்கில் பேசவும்...',
    submitting: 'Google Gemini மூலம் பகுப்பாய்வு செய்து சமர்ப்பிக்கப்படுகிறது...',
    submitReport: 'புகாரை சமர்ப்பிக்கவும்',
    priorityScore: 'முன்னுரிமை மதிப்பீடு',
    reportsCount: 'அறிக்கைகள்',
    upvotes: 'எனக்கும் இதே பிரச்சனை உள்ளது',
    statusReported: 'பதிவு செய்யப்பட்டது',
    statusInReview: 'பரிசீலனையில்',
    statusInProgress: 'பணி நடக்கிறது',
    statusResolved: 'தீர்க்கப்பட்டது',
    geminiAnalysis: 'Google Gemini மல்டிமாடல் ஏஐ ஆய்வு',
    severity: 'தீவிரத்தன்மை',
    confidence: 'ஏஐ நம்பிக்கை',
    hazard: 'ஆபத்து மதிப்பீடு',
    remediation: 'பரிந்துரைக்கப்பட்ட தீர்வு',
    duplicateNotice: 'இணைக்கப்பட்டது: 25 மீட்டருக்குள் ஏற்கனவே உள்ள புகாருடன் இணைக்கப்பட்டு முன்னுரிமை அதிகரிக்கப்பட்டது!',
    novelNotice: 'புதிய புகார் வெற்றிகரமாக பதிவு செய்யப்பட்டது.',
    filterAll: 'அனைத்து பிரிவுகள்',
    filterHighPriority: 'அதி அவசரம் (≥ 3.5)',
    filterPending: 'நடவடிக்கை தேவை',
    assignWorker: 'பணியாளரை நியமி',
    resolveIssue: 'தீர்க்கப்பட்டதாகக் குறிக்கவும்',
  },
  te: {
    appTitle: 'సివిక్ రిజాల్వ్',
    tagline: 'ఏఐ ఆధారిత పౌర సమస్యల పరిష్కార వేదిక',
    citizenMode: 'పౌరుల పోర్టల్',
    officerMode: 'మున్సిపల్ అధికారి పోర్టల్',
    reportIssue: 'సమస్యను నివేదించండి',
    reportSubtitle: 'రోడ్లు, డ్రైనేజీ తదితర సమస్యల ఫోటోలను తీసి సులభంగా పరిష్కరించుకోండి.',
    takePhoto: 'ఫోటో తీయండి / అప్‌లోడ్ చేయండి',
    voiceInput: 'వాయిస్ రిపోర్ట్ (మాట్లాడండి)',
    listening: 'వింటున్నాము... సమస్య గురించి చెప్పండి',
    locationVerified: 'జీపీఎస్ లొకేషన్ సరిచూడబడింది',
    onSiteToggle: 'నేను ప్రస్తుతం ఇక్కడే ఉన్నాను',
    categorySelect: 'సమస్య విభాగం',
    describePlaceholder: 'సమస్య వివరాలు టైప్ చేయండి లేదా మాట్లాడండి...',
    submitting: 'Google Gemini ద్వారా విశ్లేషిస్తోంది...',
    submitReport: 'నివేదికను సమర్పించండి',
    priorityScore: 'ప్రాధాన్యత స్కోరు',
    reportsCount: 'నివేదికలు',
    upvotes: 'నేను కూడా ఈ సమస్యను ఎదుర్కొన్నాను',
    statusReported: 'నమోదైంది',
    statusInReview: 'పరిశీలనలో ఉంది',
    statusInProgress: 'పని జరుగుతోంది',
    statusResolved: 'పరిష్కరించబడింది',
    geminiAnalysis: 'Google Gemini మల్టీమోడల్ విశ్లేషణ',
    severity: 'తీవ్రత',
    confidence: 'ఏఐ ఖచ్చితత్వం',
    hazard: 'ప్రమాద తీవ్రత అంచనా',
    remediation: 'సూచించిన పరిష్కారం',
    duplicateNotice: 'సమీపంలోని 25 మీటర్ల పరిధిలోని ఫిర్యాదుతో జతచేయబడింది. ప్రాధాన్యత పెంచబడింది!',
    novelNotice: 'కొత్త సమస్య విజయవంతంగా నమోదైంది.',
    filterAll: 'అన్ని విభాగాలు',
    filterHighPriority: 'అత్యవసరం (≥ 3.5)',
    filterPending: 'చర్య అవసరం',
    assignWorker: 'సిబ్బందిని కేటాయించండి',
    resolveIssue: 'పరిష్కరించినట్లు నమోదు చేయండి',
  },
  kn: {
    appTitle: 'ಸಿವಿಕ್ ರಿಸಾಲ್ವ್',
    tagline: 'ಎಐ ಆಧಾರಿತ ಸಮುದಾಯ ಮೂಲಸೌಕರ್ಯ ಪರಿಹಾರ ವೇದಿಕೆ',
    citizenMode: 'ನಾಗರಿಕ ಪೋರ್ಟಲ್',
    officerMode: 'ಪಾಲಿಕೆ ಅಧಿಕಾರಿ ಪೋರ್ಟಲ್',
    reportIssue: 'ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಿ',
    reportSubtitle: 'ರಸ್ತೆ, ಒಳಚರಂಡಿ ಮುಂತಾದ ಸಾರ್ವಜನಿಕ ಸಮಸ್ಯೆಗಳನ್ನು ವರದಿ ಮಾಡಿ.',
    takePhoto: 'ಫೋಟೋ ತೆಗೆಯಿರಿ ಅಥವಾ ಅಪ್ಲೋಡ್ ಮಾಡಿ',
    voiceInput: 'ಧ್ವನಿ ಮೂಲಕ ವರದಿ ಮಾಡಿ',
    listening: 'ಆಲಿಸಲಾಗುತ್ತಿದೆ... ದಯವಿಟ್ಟು ಮಾತನಾಡಿ',
    locationVerified: 'ಜಿಪಿಎಸ್ ಸ್ಥಳ ದೃಢೀಕರಿಸಲಾಗಿದೆ',
    onSiteToggle: 'ನಾನು ಪ್ರಸ್ತುತ ಇದೇ ಸ್ಥಳದಲ್ಲಿದ್ದೇನೆ',
    categorySelect: 'ಸಮಸ್ಯೆಯ ವರ್ಗ',
    describePlaceholder: 'ವಿವರಗಳನ್ನು ಬರೆಯಿರಿ ಅಥವಾ ಮಾತನಾಡಿ...',
    submitting: 'Google Gemini ಮೂಲಕ ವಿಶ್ಲೇಷಿಸಿ ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
    submitReport: 'ವರದಿ ಸಲ್ಲಿಸಿ',
    priorityScore: 'ಆದ್ಯತಾ ಅಂಕ',
    reportsCount: 'ವರದಿಗಳು',
    upvotes: 'ನನಗೂ ಈ ಸಮಸ್ಯೆ ಎದುರಾಗಿದೆ',
    statusReported: 'ದಾಖಲಾಗಿದೆ',
    statusInReview: 'ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ',
    statusInProgress: 'ಕೆಲಸ ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    statusResolved: 'ಪರಿಹರಿಸಲಾಗಿದೆ',
    geminiAnalysis: 'Google Gemini ಮಲ್ಟಿಮೋಡಲ್ ವಿಶ್ಲೇಷಣೆ',
    severity: 'ತೀವ್ರತೆ',
    confidence: 'ಖಚಿತತೆ',
    hazard: 'ಅಪಾಯದ ಮೌಲ್ಯಮಾಪನ',
    remediation: 'ಪರಿಹಾರ ಸಲಹೆ',
    duplicateNotice: '25 ಮೀಟರ್ ವ್ಯಾಪ್ತಿಯಲ್ಲಿ ಈಗಾಗಲೇ ಇರುವ ಸಮಸ್ಯೆಗೆ ಜೋಡಿಸಲಾಗಿದೆ.',
    novelNotice: 'ಹೊಸ ಸಮಸ್ಯೆ ದಾಖಲಾಗಿದೆ.',
    filterAll: 'ಎಲ್ಲಾ ವರ್ಗಗಳು',
    filterHighPriority: 'ಅತಿ ಮುಖ್ಯ (≥ 3.5)',
    filterPending: 'ಕ್ರಮ ಅಗತ್ಯವಿದೆ',
    assignWorker: 'ಸಿಬ್ಬಂದಿ ನಿಯೋಜಿಸಿ',
    resolveIssue: 'ಪರಿಹಾರ ಮುಗಿಸಿ',
  },
  bn: {
    appTitle: 'সিভিক রিজলভ',
    tagline: 'এআই-চালিত নাগরিক পরিকাঠামো প্ল্যাটফর্ম',
    citizenMode: 'নাগরিক পোর্টাল',
    officerMode: 'পৌরসভা অ্যাডমিন পোর্টাল',
    reportIssue: 'সমস্যা রিপোর্ট করুন',
    reportSubtitle: 'পৌরসভার দ্রুত পদক্ষেপের জন্য পরিকাঠামোগত সমস্যার ছবি তুলুন।',
    takePhoto: 'ছবি তুলুন / আপলোড করুন',
    voiceInput: 'ভয়েস দিয়ে রিপোর্ট করুন',
    listening: 'শুনছি... অনুগ্রহ করে বলুন',
    locationVerified: 'জিপিএস অবস্থান যাচাই করা হয়েছে',
    onSiteToggle: 'আমি ব্যক্তিগতভাবে এই স্থানে উপস্থিত আছি',
    categorySelect: 'সমস্যার বিভাগ',
    describePlaceholder: 'সমস্যার বিবরণ লিখুন বা মাইক ব্যবহার করুন...',
    submitting: 'Google Gemini বিশ্লেষণ করে জমা দেওয়া হচ্ছে...',
    submitReport: 'রিপোর্ট জমা দিন',
    priorityScore: 'অগ্রাধিকার স্কোর',
    reportsCount: 'রিপোর্ট সংখ্যা',
    upvotes: 'আমিও এই সমস্যার সম্মুখীন হয়েছি',
    statusReported: 'নথিভুক্ত',
    statusInReview: 'পর্যালোচনাধীন',
    statusInProgress: 'কাজ চলছে',
    statusResolved: 'সমাধান হয়েছে',
    geminiAnalysis: 'Google Gemini মাল্টিমোডাল বিশ্লেষণ',
    severity: 'গুরুতরতা',
    confidence: 'নির্ভুলতা',
    hazard: 'ঝুঁকি মূল্যায়ন',
    remediation: 'প্রস্তাবিত প্রতিকার',
    duplicateNotice: '২৫ মিটারের মধ্যে বিদ্যমান অভিযোগের সাথে যুক্ত করা হয়েছে!',
    novelNotice: 'নতুন অভিযোগ সফলভাবে দায়ের করা হয়েছে।',
    filterAll: 'সমস্ত বিভাগ',
    filterHighPriority: 'জরুরি অগ্রাধিকার (≥ 3.5)',
    filterPending: 'ব্যবস্থা গ্রহণ প্রয়োজন',
    assignWorker: 'কর্মী নিয়োগ করুন',
    resolveIssue: 'সমাধান চিহ্নিত করুন',
  },
  mr: {
    appTitle: 'सिव्हिक रिझॉल्व्ह',
    tagline: 'एआय-आधारित नागरी पायाभूत सुविधा निराकरण प्रणाली',
    citizenMode: 'नागरिक पोर्टल',
    officerMode: 'महानगरपालिका अधिकारी पोर्टल',
    reportIssue: 'तक्रार नोंदवा',
    reportSubtitle: 'खड्डे, कचरा, ड्रेनेज यांसारख्या समस्या फोटो काढून नोंदवा.',
    takePhoto: 'फोटो काढा किंवा अपलोड करा',
    voiceInput: 'आवाजाद्वारे नोंदवा (बोला)',
    listening: 'ऐकत आहे... कृपया बोला',
    locationVerified: 'जीपीएस स्थान सत्यापित',
    onSiteToggle: 'मी प्रत्यक्ष घटनास्थळी उपस्थित आहे',
    categorySelect: 'समस्येचा प्रकार',
    describePlaceholder: 'समस्येचे वर्णन करा किंवा बोला...',
    submitting: 'Google Gemini द्वारे विश्लेषण चालू आहे...',
    submitReport: 'तक्रार सबमिट करा',
    priorityScore: 'प्राधान्य गुण',
    reportsCount: 'नोंदी',
    upvotes: 'मलाही ही समस्या आली आहे',
    statusReported: 'नोंदणीकृत',
    statusInReview: 'पुनरावलोकन चालू',
    statusInProgress: 'काम प्रगतीपथावर',
    statusResolved: 'निराकरण झाले',
    geminiAnalysis: 'Google Gemini मल्टीमॉडल व्हिजन विश्लेषण',
    severity: 'तीव्रता',
    confidence: 'विश्वासार्हता',
    hazard: 'धोका मूल्यांकन',
    remediation: 'उपाययोजना',
    duplicateNotice: '२५ मीटर अंतरावरील तक्रारीशी जोडले गेले. प्राधान्य वाढवले!',
    novelNotice: 'नवीन तक्रार यशस्वीरीत्या दाखल केली गेली.',
    filterAll: 'सर्व प्रकार',
    filterHighPriority: 'अति तातडीचे (≥ 3.5)',
    filterPending: 'कारवाई आवश्यक',
    assignWorker: 'कर्मचारी नियुक्त करा',
    resolveIssue: 'पूर्ण झाल्याची नोंद करा',
  },
  gu: {
    appTitle: 'સિવિક રિઝોલ્વ',
    tagline: 'એઆઈ સંચાલિત નાગરિક સુવિધા પ્લેટફોર્મ',
    citizenMode: 'નાગરિક પોર્ટલ',
    officerMode: 'પાલિકા એડમિન પોર્ટલ',
    reportIssue: 'સમસ્યા નોંધાવો',
    reportSubtitle: 'ખાડા, ગટર કે કચરાની સમસ્યાની તસવીર લઈ તાત્કાલિક ઉકેલ મેળવો.',
    takePhoto: 'ફોટો લો અથવા અપલોડ કરો',
    voiceInput: 'બોલીને ફરિયાદ કરો',
    listening: 'સાંભળી રહ્યા છીએ... કૃપા કરીને બોલો',
    locationVerified: 'જીપીએસ સ્થાન ચકાસાયેલ',
    onSiteToggle: 'હું સ્થળ પર જ હાજર છું',
    categorySelect: 'કેટેગરી પસંદ કરો',
    describePlaceholder: 'સમસ્યાનું વર્ણન કરો અથવા માઇક વાપરો...',
    submitting: 'Google Gemini દ્વારા વિશ્લેષણ થઈ રહ્યું છે...',
    submitReport: 'ફરિયાદ સબમિટ કરો',
    priorityScore: 'પ્રાથમિકતા સ્કોર',
    reportsCount: 'રિપોર્ટસ',
    upvotes: 'મને પણ આ સમસ્યા નડી છે',
    statusReported: 'નોંધાયેલ',
    statusInReview: 'સમીક્ષા હેઠળ',
    statusInProgress: 'કામ ચાલુ છે',
    statusResolved: 'ઉકેલાયેલ',
    geminiAnalysis: 'Google Gemini મલ્ટીમોડલ વિશ્લેષણ',
    severity: 'ગંભીરતા',
    confidence: 'ચોકસાઈ',
    hazard: 'જોખમ આકારણી',
    remediation: 'સૂચવેલ ઉકેલ',
    duplicateNotice: '25 મીટરની અંદરની ફરિયાદ સાથે જોડી દેવાયું. પ્રાથમિકતા વધી!',
    novelNotice: 'નવી ફરિયાદ સફળતાપૂર્વક નોંધાઈ ગઈ.',
    filterAll: 'બધી કેટેગરી',
    filterHighPriority: 'તાત્કાલિક (≥ 3.5)',
    filterPending: 'પગલાં જરૂરી',
    assignWorker: 'કર્મચારી સોંપો',
    resolveIssue: 'ઉકેલ ચકાસો',
  }
};
